import { useCallback,useState } from 'react'
import { SearchBar } from '../components/SearchBar'
import { MovieGrid } from '../components/MovieGrid'
import { movies } from '../data/movies'
import { useInfiniteScroll } from '../hooks/useInfiniteScroll'
const PAGE_SIZE=8
const catalog=Array.from({length:4},(_,group)=>movies.map(movie=>({...movie,id:movie.id+group*100,title:group?`${movie.title} ${group+1}`:movie.title}))).flat()
export function HomePage(){const [searchTerm,setSearchTerm]=useState('');const [visibleCount,setVisibleCount]=useState(PAGE_SIZE);const normalizedSearchTerm=searchTerm.trim().toLowerCase();const filteredMovies=catalog.filter(movie=>`${movie.title} ${movie.originalTitle}`.toLowerCase().includes(normalizedSearchTerm));const hasMore=visibleCount<filteredMovies.length;const loadMore=useCallback(()=>setVisibleCount(count=>Math.min(count+PAGE_SIZE,filteredMovies.length)),[filteredMovies.length]);const loadMoreRef=useInfiniteScroll({hasMore,onLoadMore:loadMore});const changeSearch=(value:string)=>{setSearchTerm(value);setVisibleCount(PAGE_SIZE)};const resetSearch=()=>changeSearch('');return <><section className="hero"><div><h1>오늘은 어떤 영화를 찾아볼까요?</h1><p>새로운 이야기와 오래 기억될 장면을 만나보세요.</p><SearchBar value={searchTerm} onChange={changeSearch} onReset={resetSearch}/></div></section><section className="content"><div className="section-heading"><div><h2>{normalizedSearchTerm?`“${searchTerm.trim()}” 검색 결과`:'추천 영화'}</h2><p>{Math.min(visibleCount,filteredMovies.length)} / {filteredMovies.length}개 영화</p></div></div>{filteredMovies.length>0?<><MovieGrid movies={filteredMovies.slice(0,visibleCount)}/>{hasMore?<div className="load-more" ref={loadMoreRef} aria-hidden="true">다음 영화를 불러오는 중...</div>:<p className="end-message">모든 영화를 확인했습니다.</p>}</>:<div className="empty-state"><strong>검색 결과가 없습니다.</strong><p>다른 검색어를 입력해보세요.</p><button type="button" onClick={resetSearch}>검색 초기화</button></div>}</section></>}
export default HomePage
